@startuml Excluir Usuário
actor Cliente

Cliente -> api.php : DELETE /api/user
api.php -> UsuarioController : destroy(request)
UsuarioController -> UsuarioService : agendarExclusaoUsuario(id)
UsuarioService -> Usuario : save([status="Exclusao Pendente"])
Usuario --> UsuarioService : Sucesso
UsuarioService --> UsuarioController : id
UsuarioController --> Cliente : Response status 202 + message:"Usuário em processo de exclusão" + id

@enduml
